grafana:
  env:
    GF_SERVER_DOMAIN: "81.26.178.30"
    GF_SERVER_ROOT_URL: "http://81.26.178.30/grafana/"
    GF_SERVER_SERVE_FROM_SUB_PATH: "true"

  ingress:
    enabled: false 

prometheus:
  prometheusSpec:
    web:
      routePrefix: /prometheus

